### PR TITLE
Add a format checker to the CI pipeline

### PR DESCRIPTION
**Pull request by swift-kim**
- Add the `format` job to the CI pipeline.
  - ~The linter job will be added in the future.~ (The lint warning/errors will not be analyzed by the CI.)
- Format GN files.
- Format C/C++ files using the Chromium style (as defined in the [`.clang-format`](https://github.com/flutter-tizen/engine/blob/flutter-2.0.1-tizen/.clang-format) file).

For maintainers: The Chromium C/C++ style is slightly different from the Google C/C++ style, but you don't need any special configuration if everything works correctly. clang-format and the VS Code extension should just work out of the box. They will find the `.clang-format` file from the repository root automatically.

To manually analyze code formatting, you can use either:
- [check_tidy.py](https://github.com/flutter-tizen/plugins/pull/93) (`check_tidy.py --dir shell/platform/tizen`)
- format.dart (`ci/format.sh`)
  - You must add this to your Git remote endpoints: `git remote add upstream https://github.com/flutter/engine.git`

### CODE REVIEW

**Comment by bbrto21** [comment]
> the `.clang-format` file from the repository root automatically.

I didn't know there was this, What do you think about replacing the plugin repository ```.clang-format``` with this?

**Comment by swift-kim** [comment]
@bbrto21 The first-party plugins also follow the Google style (https://github.com/flutter/plugins/blob/master/.clang-format) so I think we can leave as it is.

**Comment by bbrto21** [comment]
@swift-kim Oh, thank you for checking!

**Review by bbrto21 — APPROVED** [review]
LGTM

**Pull request merged**
