### PR TITLE
Add vulkan renderer

### PR DESCRIPTION
**Pull request by zhouleonlei**
Add vulkan renderer based on the Ecore window.

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by zhouleonlei** [comment]
> I tried to use this, but it didn't work. And I got the following log:
> 
> ```
> E/ConsoleMessage( 3025): FlutterApplication.cs: Run(116) > Unhandled exception: System.DllNotFoundException: Unable to load shared library 'flutter_tizen.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libflutter_tizen.so: cannot open shared object file: No such file or directory
> E/ConsoleMessage( 3025):    at Tizen.Flutter.Embedding.Interop.FlutterDesktopEngineCreate(FlutterDesktopEngineProperties& engine_properties)
> E/ConsoleMessage( 3025):    at Tizen.Flutter.Embedding.FlutterEngine..ctor(String assetsPath, String icuDataPath, String aotLibraryPath, String dartEntrypoint, List`1 dartEntrypointArgs) in /home/boram/Work/f-project/flutter-tizen/embedding/csharp/Tizen.Flutter.Embedding/FlutterEngine.cs:line 54
> E/ConsoleMessage( 3025):    at Tizen.Flutter.Embedding.FlutterEngine..ctor(String dartEntrypoint, List`1 dartEntrypointArgs) in /home/boram/Work/f-project/flutter-tizen/embedding/csharp/Tizen.Flutter.Embedding/FlutterEngine.cs:line 29
> E/ConsoleMessage( 3025):    at Tizen.Flutter.Embedding.FlutterApplication.OnCreate() in /home/boram/Work/f-project/flutter-tizen/embedding/csharp/Tizen.Flutter.Embedding/FlutterApplication.cs:line 126
> E/ConsoleMessage( 3025):    at Runner.App.OnCreate() in /home/boram/Work/f-project/sample/gallery/tizen/App.cs:line 10
> E/ConsoleMessage( 3025):    at Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(IntPtr data)
> E/ConsoleMessage( 3025):    at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
> E/ConsoleMessage( 3025):    at Tizen.Applications.CoreApplication.Run(String[] args)
> E/ConsoleMessage( 3025):    at Tizen.Applications.CoreUIApplication.Run(String[] args)
> E/ConsoleMessage( 3025):    at Tizen.Flutter.Embedding.FlutterApplication.Run(String[] args) in /home/boram/Work/f-project/flutter-tizen/embedding/csharp/Tizen.Flutter.Embedding/FlutterApplication.cs:line 119
> E/ConsoleMessage( 3025):    at Runner.App.Main(String[] args) in /home/boram/Work/f-project/sample/gallery/tizen/App.cs:line
> ```

Hello
Which device did you use?
Please install rpms below:
1. Driver 
TV(PONTUSM, NIKEM2) ---> soc-gpu-ddk-nike-tv-23.0-0.armv7l.rpm
RPI4 --->mesa-22.1.7-0.armv7l.rpm
2. vulkan-headers-1.3.208-0.armv7l.rpm
3. vulkan-loader-1.3.208-0.armv7l.rpm
4. vulkan-wsi-layer-1.0.5-0.armv7l.rpm

Thanks

**Comment by bbrto21** [comment]
I used TM1 and mobile emulator. both are Tizen 6.5. Why do I need to install more rpms manually?

**Comment by xuelian-bai** [comment]
> I used TM1 and mobile emulator. both are Tizen 6.5. Why do I need to install more rpms manually?

I think you can't run vulkan on emluator. On emulator, GLES API is translated into GL API via yagl module, though vulkan is cross-platform, yagl still need to do something to forward vulkan API, I think this part isn't implemented yet.

**Comment by zhouleonlei** [comment]
> I used TM1 and mobile emulator. both are Tizen 6.5. Why do I need to install more rpms manually?

Why do I need to install more rpms manually?
--->Because current Tizen images didn't include vulkan related libraries and header flies

**Comment by swift-kim** [comment]
You may reopen this in https://github.com/flutter-tizen/embedder if necessary.

**Comment by swift-kim** [comment]
Can external textures be used with the Vulkan renderer?

**Comment by xuelian-bai** [comment]
no, it can't, it's not fully implemented

**Comment by swift-kim** [comment]
Yeah, it's not (yet) implemented. Is it technically possible to implement the external texture support in the future?

**Comment by xuelian-bai** [comment]
it's possible, we have implemented prototype last year, but since Impeller could be used in the future,  we have suspend this implementation, and didn't fixed bugs. 
On the other way, since skia is designed for opengl, even we use vulkan backend, performance may not be enhanced, Imepller is designed for modern graphic APIs(Vulkan, metal), so I guess using impeller vulkan backend will have better performance.

**Pull request closed without merging**
