### PR TITLE
Fix parsing bug for dispose method

### PR DESCRIPTION
**Pull request by seungsoo47**
In PlatformViewChannel::HandleMethodCall, a argument for 'dispose' method includes a map.
Hence, to get a proper view_id value, it should be parsed by 'id' key.

### CODE REVIEW

**Review by bbrto21 — APPROVED** [review]
LGTM

**Review by bwikbs — APPROVED** [review]
Thanks! :+1:

**Comment by swift-kim** [comment]
Shouldn't this be fixed in the plugin side?

https://github.com/flutter-tizen/plugins/blob/efe670a35d818a29731e079ac412ec0cd0a78ec6/packages/webview_flutter/lib/src/platform_view_tizen.dart#L261-L265

should be

```dart
await SystemChannels.platform_views.invokeMethod<void>('dispose', viewId);
```

**Comment by seungsoo47** [comment]
https://github.com/flutter-tizen/engine/blob/bdd0af41e669e3181cab01649a354965a01baf39/shell/platform/tizen/channels/platform_view_channel.cc#L180-L184
It was initially handled using map value.

**Comment by swift-kim** [comment]
> It was initially handled using map value.

It doesn't matter.

**Review by swift-kim — APPROVED** [review]
Anyway the change looks good to me.

**Pull request merged**
