### PR TITLE
Remove background and set alpha as true on Evas gl

### PR DESCRIPTION
**Pull request by bbrto21**
* This patch fix a blank screen issue when launching time.
  What was shown as a blank screen is the background color of the elm_win.
* Restriction:
  This patch doesn't fix the blank screen issue between the splash screen and the first frame.

Signed-off-by: Boram Bae <boram21.bae@samsung.com>

### CODE REVIEW

**Comment by bwikbs** [comment]
I don't know about this issue(also efl), but if we remove the background object , it might be a problem when other evas objects are added win later. 
( It may not be a problem by setting alpha or using evas gl )
If the problem is that the screen is visible before starting the app, how about not showing it until ready?

**Comment by bbrto21** [comment]
>I don't know about this issue(also efl), but if we remove the background object , it might be a problem when other evas objects are added win later.

Could you give me a detail to reproduce that you worried? I'll check it out. 

> If the problem is that the screen is visible before starting the app, how about not showing it until ready?

@bwikbs  Do you have any ideas? If we can know that the first frame is ready, I guess this problem can be solved.

>* Restriction:
> This patch doesn't fix the blank screen issue between the splash screen and the first frame.

**Comment by bwikbs** [comment]
@bbrto21 
> Could you give me a detail to reproduce that you worried? I'll check it out.

I mean (I already written that way...) It doesn't mean it's happening now. It wouldn't be rendered if an evas object was added here in the future(Maybe plugin?) and it didn't overlap with anything else. 
That's all I'm concerned.

> Do you have any ideas? If we can know that the first frame is ready, I guess this problem can be solved.

To be honest, I have ``TizenVsyncWaiter`` in mind. but I'm not sure as I've never seen a related issue.
So.. If you want, I'll look at the way of getting the first frame from that issue.

**Comment by bbrto21** [comment]
> I don't know about this issue(also efl), but if we remove the background object , it might be a problem when other evas objects are added win later.

I still didn't understand what you said. Can't it added another evas_object to elm_win without background? 

> To be honest, I have `TizenVsyncWaiter` in mind. but I'm not sure as I've never seen a related issue.
> So.. If you want, I'll look at the way of getting the first frame from that issue.

of course. this problem has existed since the introduction of the Evas gl renderer, and recently raised as a issue during the development of the splash screen plugin. please feel free to fix it.

**Comment by bwikbs** [comment]
> I still didn't understand what you said. Can't it added another evas_object to elm_win without background?

Here's an old blog for you. 
http://egloos.zum.com/seoz/v/3904325
Here is a brief explanation of why efl starts with a single background. 
I'm worried about is this part.

**Comment by bbrto21** [comment]
> http://egloos.zum.com/seoz/v/3904325

Even reading this, I cannot understand your concerns. I made the window as transparent and remove the background.

**Comment by bwikbs** [comment]
I am middle of fixing my comment, but you already answered it! 
Still not enough answers?

**Comment by bbrto21** [comment]
> * Restriction:
>   This patch doesn't fix the blank screen issue between the splash screen and the first frame.

This is not perfect solution, so I closed this PR

**Pull request closed without merging**
