### PR TITLE
Migrate to the new GpuSurfaceTexture API

### PR DESCRIPTION
**Pull request by swift-kim**
Migrate from the outdated [`FlutterDesktopGpuBuffer`](https://github.com/flutter-tizen/engine/blob/flutter-3.0.5-tizen/shell/platform/common/public/flutter_texture_registrar.h)-based APIs to the official [`FlutterDesktopGpuSurfaceDescriptor`](https://github.com/flutter-tizen/engine/blob/flutter-3.3.0-tizen/shell/platform/common/public/flutter_texture_registrar.h)-based APIs.

Contributes to https://github.com/flutter-tizen/engine/issues/285.

Plugins that use the relevant texture API must be updated as well.

### CODE REVIEW

**Comment by bwikbs** [comment]
Now I can build this branch! :smile:

**Comment by JSUYA** [comment]
https://github.com/flutter-tizen/engine/runs/8150324971?check_suite_focus=true#step:6:290
It's probably clang-format version 15.
How about changing clang_format_path of visual code tool to clang-format of llvm-project?

**Review by bwikbs — APPROVED** [review]
:+1:

**Comment by swift-kim** [comment]
@JSUYA Hmm. Developers do not use their IDE for engine development only so setting `clang_format_path` to the engine toolchain's clang-format path doesn't seem a very good solution. Most developers should not have any problem if they don't specify `clang_format_path` and just use clang-format bundled with the latest C/C++ extension. For CLI users, I'd recommend to download and install clang-format-15 directly from https://apt.llvm.org/. I'll update https://github.com/flutter-tizen/flutter-tizen/wiki/Style-guide soon.

**Pull request merged**
