### PR TITLE
Pass only a preferred language to the engine

### PR DESCRIPTION
**Pull request by swift-kim**
Potentially fixes https://github.com/flutter-tizen/flutter-tizen/issues/184. More testing is required.

### CODE REVIEW

**Comment by swift-kim** [comment]
The previous change (e9e4bf630e7a87f1b166043de790fe16110dae31) was still okay for usual cases, but I wanted the implementation to be robust enough to handle special cases like `zh_Hans_CN` and decided to use `i18n_ulocale` again.

Please refer to https://flutter.dev/docs/development/accessibility-and-localization/internationalization for a simple reproduction case.

**Comment by bwikbs** [comment]
I'm little confused..  the previous change (e9e4bf630e7a87f1b166043de790fe16110dae31) has only filename change. (What am I missing?) and ``i18n_ulocale`` stuff  was used at that time too? :eyes:

**Comment by swift-kim** [comment]
@bwikbs Basically the both implementations (`system_utils_tizen.cc` and `system_utils_linux.cc`) work in the same way - they obtain the system's preferred language using the `LANG` environment variable. Thus it is technically possible to use `system_utils_linux.cc` for both Linux and Tizen.

`i18n_ulocale` is only used for extracting values such as `language`, `territory`, and `script` from a locale.

**Comment by bwikbs** [comment]
@swift-kim Now I understand! Thanks! :heart:

**Review by bbrto21 — APPROVED** [review]
LGTM

**Review by bwikbs — APPROVED** [review]

**Pull request merged**
