### PR TITLE
[ci] Change the release tag format

### PR DESCRIPTION
**Pull request by swift-kim**
As GitHub doesn't any more support a release tag name identical to the target commit hash ([404 Not Found error](https://github.com/flutter-tizen/plugins/pull/387#issuecomment-1128314187)), we need to use a different format for the tag name.

Old: Short commit hash (e.g. `abcdefg`)
New: Engine version + short commit hash (e.g. `3.0.0-abcdefg`)

Any suggestion? @flutter-tizen/maintainers

### CODE REVIEW

**Comment by swift-kim** [comment]
There's still no response to my GitHub support ticket, and an action should be made as soon as possible (hopefully today). This change doesn't seem to be a bad idea.

**Comment by xuelian-bai** [comment]
looks good to me

**Comment by HakkyuKim** [comment]
Looks good to me as well, maybe engine.version need to be changed in tools?

**Comment by swift-kim** [comment]
@HakkyuKim Yes, right. I'll do that in https://github.com/flutter-tizen/flutter-tizen/pull/366 when this PR gets merged.

**Review by xiaowei-guan — APPROVED** [review]
Looks good to me

**Pull request merged**
