### PR TITLE
Support partial window

### PR DESCRIPTION
**Pull request by bwikbs**
Preparation work for https://github.com/flutter-tizen/engine/issues/94

- Now it is possible to create a partial app instead of a full screen as follows:
```C++
  Ecore_Wl2_Display* ecore_wl2_display_ = nullptr;
  ecore_wl2_init();
  ecore_wl2_display_ = ecore_wl2_display_connect(nullptr);
  ecore_wl2_sync();
  Ecore_Wl2_Window* ecore_wl2_window_ =
      ecore_wl2_window_new(ecore_wl2_display_, nullptr, 100, 100, 500, 600);
  ecore_wl2_window_type_set(ecore_wl2_window_,
                            ECORE_WL2_WINDOW_TYPE_TOPLEVEL);
  ecore_wl2_window_alpha_set(ecore_wl2_window_, false);
  ecore_wl2_window_position_set(ecore_wl2_window_, 0, 0);
  ecore_wl2_window_aux_hint_add(ecore_wl2_window_, 0,
                                "wm.policy.win.user.geometry", "1");
  
  FlutterDesktopEngineProperties engine_prop = {};
  engine_prop.assets_path = assets_path.c_str();
  engine_prop.icu_data_path = icu_data_path.c_str();
  engine_prop.aot_library_path = aot_lib_path.c_str();
  engine_prop.switches = switches.data();
  engine_prop.switches_count = switches.size();
  engine_prop.custom_win = ecore_wl2_window_;
```

### CODE REVIEW

**Comment by bbrto21** [comment]
After #90, we use Chromium style

**Comment by bwikbs** [comment]
Thanks for your tip.

**Comment by xuelian-bai** [comment]
I don't know about this scenario, but I'm curious what's the reason to create the window outside embedder?

**Comment by bwikbs** [comment]
> Preparation work for #94

Considering various situations, multi-screen support in Flutter is still in early stage.  So.. using multiple windows and  ``FlutterEngineGroup``(https://flutter.dev/docs/development/add-to-app/multiple-flutters) Is being considered as an alternative.

**Comment by swift-kim** [comment]
> Considering various situations, multi-screen support in Flutter is still in early stage.

Could you share your findings on this, why you're using this approach (creating a window in the app side), and what you're eventually going to implement (overall design) in #94? I don't understand how this change is even related to multi-window support so far.

**Comment by bwikbs** [comment]
> Could you share your findings on this

```
https://docs.google.com/document/d/11_4wntz_9IJTQOo_Qhp7QF4RfpIMTfVygtOTxQ4OGHY/edit
https://github.com/flutter/flutter/issues/30701
https://github.com/google/flutter-desktop-embedding/issues/98
```

>  why you're using this approach (creating a window in the app side)

This is android sample of ``FlutterEngineGroup`` 

```java
class EngineBindings(activity: Activity, delegate: EngineBindingsDelegate, entrypoint: String) :
    DataModelObserver {
    val channel: MethodChannel
    val engine: FlutterEngine
    val delegate: EngineBindingsDelegate

    init {
        val app = activity.applicationContext as App
        // This has to be lazy to avoid creation before the FlutterEngineGroup.
        val dartEntrypoint =
            DartExecutor.DartEntrypoint(
                FlutterInjector.instance().flutterLoader().findAppBundlePath(), entrypoint
            )
        engine = app.engines.createAndRunEngine(activity, dartEntrypoint)
        this.delegate = delegate
        channel = MethodChannel(engine.dartExecutor.binaryMessenger, "multiple-flutters")
    }
```

As you can see, ``FlutterEngineGroup`` is part of

**Comment by xuelian-bai** [comment]
I checked the android sample, it is showing sample of enginegroup, which share resources when multiple engines exist,  but I still don't understand why create a window in app, instead of using the window inside embedder.

**Comment by swift-kim** [comment]
Could we move the discussion to #94? 🙂

**Comment by bwikbs** [comment]
Go on https://github.com/flutter-tizen/engine/pull/114

**Pull request closed without merging**
