### PR TITLE
Fix a pointer event bug

### PR DESCRIPTION
**Pull request by bbrto21**
* Calculate relative coordinates before delegating to the FlutterTizenView.

Signed-off-by: Boram Bae <boram21.bae@samsung.com>

### CODE REVIEW

**Comment by swift-kim** [comment]
Could you describe what the bug was?

Does this change work for all possible cases, including `TizenWindowElementary`/`TizenWindowEcoreWl2`/`TizenViewElementary` and landscape/portrait?

**Comment by bbrto21** [comment]
> Could you describe what the bug was?

It caused by recent changes and can only be reproduced when the view type is `Window`.  especially it happens when you use the window channel to move the window. you must change the mouse coordinates to relative coordinates only when the view type is not Window. The orientation of the device is irrelevant.

**Review by JSUYA — APPROVED** [review]

**Comment by swift-kim** [comment]
@bbrto21 So what is the bug? What's not working?

**Comment by bbrto21** [comment]
> @bbrto21 So what is the bug? What's not working?

The mouse event coordinates are reduced by the distance the window moves.

**Review by swift-kim — APPROVED** [review]

**Pull request merged**
