### PR TITLE
Ignore SystemChrome.setApplicationSwitcherDescription

### PR DESCRIPTION
**Pull request by swift-kim**
Do not print the "unimplemented method" warning when run with the `--verbose-system-logs` option. The method is always called when the [Title](https://api.flutter.dev/flutter/widgets/Title-class.html) widget rebuilds.

### CODE REVIEW

**Review by JSUYA — COMMENTED** [review]
I think it's an appropriate message because it's actually unimplemented.
Is there any reason why we should hide this?

**Comment by swift-kim** [comment]
@JSUYA The Tizen platform doesn't support the functionality in the first place, so "unimplemented" is in fact misleading. It'd be better to make it just no-op.

**Review by JSUYA — APPROVED** [review]
um.. If it is not supported, I think it may better print "unsupported".
Anyway. I got it.

**Comment by swift-kim** [comment]
The [API documentation](https://api.flutter.dev/flutter/services/SystemChrome/setApplicationSwitcherDescription.html) says

> Any part of the description that is unsupported on the current platform will be ignored.

so it should be safe to return `Success` instead of `NotImplemented`.

**Review by bbrto21 — APPROVED** [review]

**Review by JSUYA — APPROVED** [review]

**Pull request merged**
