### PR TITLE
Refactor TizenRenderers

### PR DESCRIPTION
**Pull request by swift-kim**
Common
- Merge `InitializeRenderer` and `DestroyRenderer` into constructors and destructors.
- Inline `GetWindowHandle`.
- Code cleanups.

Ecore Wl2
- Combine `SetupDisplay` and `SetupEcoreWlWindow` into a single function `SetupEcoreWl2`.
- Combine `SetupEglWindow` and `SetupEglSurface` into a single function `SetupEGL`.
- Remove unnecessary private methods.
- Add additional error descriptions for EGL errors.

Evas GL
- Let `SetupEvasWindow` return bool to make the calling order consistent with Ecore Wl2.

### CODE REVIEW

**Comment by bwikbs** [comment]
The refactoring is neat and great! :+1: 
And.. What motivated you to do this? I wonder what's bothering you :smile:

**Comment by swift-kim** [comment]
@bwikbs I was writing [`TizenRendererWayland`](https://github.com/swift-kim/engine/commit/505cbda0e19bbf31e4b095c510c0256587f1b8b9) (just for fun), and wanted to make the code style consistent across the renderers. :)

**Comment by bwikbs** [comment]
@swift-kim 
You really hate ``efl``!!!  :smile:

**Review by bwikbs — APPROVED** [review]
I forgot this! It's pretty cool! :+1:

**Pull request merged**
