### PR TITLE
Replace LocalizationChannel with system_utils

### PR DESCRIPTION
**Pull request by swift-kim**
- Remove `LocalizationChannel`, because it doesn't act like a channel or plugin.
- Create `system_utils.h`, similarly to other platform embedders. More functions may be added in this file in the future.
- Implement `system_utils_tizen.cc` and `system_utils_linux.cc` for the Tizen and Linux x64 embedders respectively.

Note: 
- Some code was copied from the Windows and GLFW embedders.
- The `SendPlatformResolvedLocale` method has been removed because [it's not used by anything](https://github.com/flutter/engine/pull/19136). The functionality has been moved to the embedder API (`FlutterProjectArgs.compute_platform_resolved_locale_callback`). I don't think we need to implement it.

@bbrto21 and I have agreed to use the `_tizen.cc` and `_linux.cc` filename suffixes for Tizen and Linux-specific implementations. How do you think? @bwikbs (The use of `_stub.cc` is to indicate the "unimplemented" state of the code and should be eliminated eventually.)

### CODE REVIEW

**Comment by bwikbs** [comment]
> @bbrto21 and I have agreed to use the _tizen.cc and _linux.cc filename suffixes for Tizen and Linux-specific implementations. How do you think? @bwikbs (The use of _stub.cc is to indicate the "unimplemented" state of the code and should be eliminated eventually.)

I totally agree with you! The only reason I'm wary of the _linux suffix is that the linux port is already in use. 
If you guys opinion is so, I would like to use it that way.

**Comment by bwikbs** [comment]
I got following error code at x64 build
```
../../flutter/shell/platform/tizen/flutter_tizen_engine.cc:47:15: error: unused function 'CovertToFlutterLocale' [-Werror,-Wunused-function]
FlutterLocale CovertToFlutterLocale(const LocaleInfo& info) {
```

**Comment by swift-kim** [comment]
@bwikbs Uh, my mistake. Something went wrong during the last rebase. The error should have been fixed now.

**Review by bbrto21 — APPROVED** [review]
LGTM!

**Review by bwikbs — APPROVED** [review]
Thanks! It's pretty cool :+1:

**Pull request merged**
