### PR TITLE
Fix a crash during app shutdown

### PR DESCRIPTION
**Pull request by bbrto21**
This PR includes:

* Disconnect Ecore_Wl2_Display instead of destroy
* Correct the order of resource release.

Signed-off-by: Boram Bae <boram21.bae@samsung.com>

### CODE REVIEW

**Comment by swift-kim** [comment]
Currently unresolved errors during app shutdown:

TW3 Platform 6.0 (tizen-unified_20201013.2_wearable-wayland-armv7l-tw3):
```
D/ConsoleMessage(11451): ../../flutter/shell/platform/tizen/tizen_surface_gl.cc: Destroy(353) > Destroy
E/MALI(11451): ==>[ERROR] (Runner.dll) [EGL] egl/src/mali_egl_surface_common.c:860 eglDestroySurface 0x3001:EGL_NOT_INITIALIZED in eglDestroySurface
E/MALI(11451): ==>[ERROR] (Runner.dll) [EGL] egl/src/mali_egl_surface_common.c:860 eglDestroySurface 0x3001:EGL_NOT_INITIALIZED in eglDestroySurface
E/MALI(11451): ==>[ERROR] (Runner.dll) [EGL] egl/src/mali_egl_context.c:622 eglDestroyContext 0x3001:EGL_NOT_INITIALIZED in eglDestroyContext
E/ConsoleMessage(11451): ../../flutter/shell/platform/tizen/tizen_surface_gl.cc: ~TizenEGLContext(97) > Failed to destroy egl context
E/MALI(11451): ==>[ERROR] (Runner.dll) [EGL] egl/src/mali_egl_context.c:622 eglDestroyContext 0x3001:EGL_NOT_INITIALIZED in eglDestroyContext
E/ConsoleMessage(11451): ../../flutter/shell/platform/tizen/tizen_surface_gl.cc: ~TizenEGLContext(101) > Failed to destroy egl resource context
```

Galaxy Watch 5.5 (PLATFORM_DayR800XX_20200611.001):
```
I/ConsoleMessage(27407): globalapps/dev.flutter.jsonexample/bin/Runner.dll: tpl_wayland_egl.c:725: __tpl_wayland_egl_surface_fini: Assertion `wl_egl_window' failed.
I/ConsoleMessage(27407): onSigabrt called
```

**Comment by bbrto21** [comment]
> Currently unresolved errors during app shutdown:
> 
> TW3 Platform 6.0 (tizen-unified_20201013.2_wearable-wayland-armv7l-tw3):
> 
> ```
> D/ConsoleMessage(11451): ../../flutter/shell/platform/tizen/tizen_surface_gl.cc: Destroy(353) > Destroy
> E/MALI(11451): ==>[ERROR] (Runner.dll) [EGL] egl/src/mali_egl_surface_common.c:860 eglDestroySurface 0x3001:EGL_NOT_INITIALIZED in eglDestroySurface
> E/MALI(11451): ==>[ERROR] (Runner.dll) [EGL] egl/src/mali_egl_surface_common.c:860 eglDestroySurface 0x3001:EGL_NOT_INITIALIZED in eglDestroySurface
> E/MALI(11451): ==>[ERROR] (Runner.dll) [EGL] egl/src/mali_egl_context.c:622 eglDestroyContext 0x3001:EGL_NOT_INITIALIZED in eglDestroyContext
> E/ConsoleMessage(11451): ../../flutter/shell/platform/tizen/tizen_surface_gl.cc: ~TizenEGLContext(97) > Failed to destroy egl context
> E/MALI(11451): ==>[ERROR] (Runner.dll) [EGL] egl/src/mali_egl_context.c:622 eglDestroyContext 0x3001:EGL_NOT_INITIALIZED in eglDestroyContext
> E/ConsoleMessage(11451): ../../flutter/shell/platform/tizen/tizen_surface_gl.cc: ~TizenEGLContext(101) > Failed to destroy egl resource context
> ```
> 
> Galaxy Watch 5.5 (PLATFORM_DayR800XX_20200611.001):
> 
> ```
> I/ConsoleMessage(27407): globalapps/dev.flutter.jsonexample/bin/Runner.dll: tpl_wayland_egl.c:725: __tpl_wayland_egl_surface_fini: Assertion `wl_egl_window' failed.
> I/ConsoleMessage(27407): onSigabrt called
> ```

I found the cause. I will fix it soon.

**Comment by bbrto21** [comment]
@swift-kim I updated this PR to fix remaining issues.

**Review by bwikbs — APPROVED** [review]

**Review by seungsoo47 — COMMENTED** [review]
LGTM

**Pull request merged**
